using System;
using System.Collections.Generic;
using System.Text;

namespace ItalianToolkit.Transports.Models
{
    public enum PlateType
    {
        Unknown = 0,
        Car,
        Motorcycle,
        Motorbike,

        CivilProtectionAosta,
        CivilProtectionBolzano,
        CivilProtectionDepartment,
        CivilProtectionFriuli,
        CoastGuard,
        CoastGuardDepartment,
        CoastGuardMotorbike,
        CoastGuardTrailer,
        ConsularCorps,
        DiplomaticCorps,
        FinanceGuard,
        FinanceGuardMotorbike,
        FinanceGuardTrailer,
        FireFighters,
        FireFightersBolzano,
        FireFightersTrailer,
        FireFightersTestVehicle,
        FireFightersTrento,
        ForeignExcursionists,
        ForestryCorps,
        ForestryCorpsAgrigento,
        ForestryCorpsAosta,
        ForestryCorpsBolzano,
        ForestryCorpsCagliari,
        ForestryCorpsCaltanissetta,
        ForestryCorpsCarboniaIglesias,
        ForestryCorpsCatania,
        ForestryCorpsEnna,
        ForestryCorpsFriuli,
        ForestryCorpsMedioCampidano,
        ForestryCorpsMessina,
        ForestryCorpsNuoro,
        ForestryCorpsOgliastra,
        ForestryCorpsOlbiaTempio,
        ForestryCorpsOristano,
        ForestryCorpsPalermo,
        ForestryCorpsRagusa,
        ForestryCorpsSassari,
        ForestryCorpsSiracusa,
        ForestryCorpsSudSardegna,
        ForestryCorpsTrapani,
        ForestryCorpsTrento,
        ItalianAirForce,
        ItalianAirForceMotorbike,
        ItalianArmy,
        ItalianArmyMotorbike,
        ItalianArmyTank,
        ItalianArmyTrailer,
        ItalianRedCross,
        ItalianRedCrossMotorbike,
        PenitentiaryPolice,
        SovereignMilitaryOrderOfMalta,
        SovereignMilitaryOrderOfMaltaMotorbike,
        StatePolice,
        TestVehicle,
        UnitedNations,
        UnitedNationsStaff,
        UnitedNationsInTransit
    }
}
